from selenium.webdriver.common.by import By


class OrangeHRMNavbar:
    side_navbar = (By.XPATH, "//nav[@aria-label='Sidepanel']")
    navbar_toggle = (By.XPATH, "//button[@class='oxd-icon-button oxd-main-menu-button']")
    navbar_banner = (By.XPATH, "//img[@alt='client brand banner']")
    navbar_logo = (By.XPATH, "//img[@alt='client brand logo']")
    navbar_search_icon = (By.XPATH, "//*[@class='oxd-icon oxd-menu-icon']")
    navbar_search_field = (By.XPATH, "//input[@placeholder='Search']")
    navbar_admin_icon = (By.XPATH, "(//*[@class='oxd-icon oxd-main-menu-item--icon'])[1]")
    navbar_admin = (By.XPATH, "//span[text()='Admin']")
    navbar_pim_icon = (By.XPATH, "(//*[@class='oxd-icon oxd-main-menu-item--icon'])[2]")
    navbar_pim = (By.XPATH, "//span[text()='PIM']")
    navbar_leave_icon = (By.XPATH, "(//*[@class='oxd-icon oxd-main-menu-item--icon'])[3]")
    navbar_leave = (By.XPATH, "//span[text()='Leave']")
    navbar_time_icon = (By.XPATH, "(//*[@class='oxd-icon oxd-main-menu-item--icon'])[4]")
    navbar_time = (By.XPATH, "//span[text()='Time']")
    navbar_recruitment_icon = (By.XPATH, "(//*[@class='oxd-icon oxd-main-menu-item--icon'])[5]")
    navbar_recruitment = (By.XPATH, "//span[text()='Recruitment']")
    navbar_my_info_icon = (By.XPATH, "(//*[@class='oxd-icon oxd-main-menu-item--icon'])[6]")
    navbar_my_info = (By.XPATH, "//span[text()='My Info']")
    navbar_performance_icon = (By.XPATH, "(//*[@class='oxd-icon oxd-main-menu-item--icon'])[7]")
    navbar_performance = (By.XPATH, "//span[text()='Performance']")
    navbar_dashboard_icon = (By.XPATH, "(//*[@class='oxd-icon oxd-main-menu-item--icon'])[8]")
    navbar_dashboard = (By.XPATH, "//span[text()='Dashboard']")
    navbar_directory_icon = (By.XPATH, "(//*[@class='oxd-icon oxd-main-menu-item--icon'])[9]")
    navbar_directory = (By.XPATH, "//span[text()='Directory']")
    navbar_maintenance_icon = (By.XPATH, "(//*[@class='oxd-icon oxd-main-menu-item--icon'])[10]")
    navbar_maintenance = (By.XPATH, "//span[text()='Maintenance']")
    navbar_buzz_icon = (By.XPATH, "(//*[@class='oxd-icon oxd-main-menu-item--icon'])[11]")
    navbar_buzz = (By.XPATH, "//span[text()='Buzz']")
